[package]
name = "board_game"
edition = { workspace = true }
rust-version = "1.81"

[[bin]]
name = "board_game"
path = "src/main.rs"
required-features = ["sp1"]
test = false

[dependencies]
smt-token = { workspace = true, default-features = false }

sdk = { workspace = true, features = ["tracing"] }
client-sdk = { workspace = true, default-features = false, features = [
    "sp1",
    "rest",
], optional = true }


anyhow = "1.0.96"
serde = { version = "1.0", default-features = false, features = [
    "derive",
    "alloc",
] }
borsh = { version = "1.5.7" }
uuid = { version = "1.6", features = ["serde"], default-features = false }

sp1-zkvm = { version = "=5.0.0", default-features = false, optional = true }

[dev-dependencies]
# Active client feature for tests
board_game = { path = ".", features = ["client"] }
clap = { version = "4.5.23", features = ["derive"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio = { version = "1.44.2", features = ["full", "tracing"] }

[features]
default = []
client = ["dep:client-sdk"]
sp1 = ["dep:sp1-zkvm", "sdk/sp1"]
