FROM oven/bun:latest AS build

WORKDIR /app

COPY front .
COPY wallet-wrapper ../wallet-wrapper

WORKDIR /wallet-wrapper
RUN rm bun.lock && rm -rf node_modules
RUN bun install && bun run build

WORKDIR /app

RUN rm bun.lock && rm -rf node_modules
RUN bun install && bun run build

FROM nginx:1.21.5-alpine AS production

COPY --from=build /app/dist /usr/share/nginx/html
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

