FROM rust:1.84 as builder
WORKDIR /usr/src/app

# Install build dependencies
RUN apt-get update && apt-get install -y \
    pkg-config \
    libdbus-1-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy your source code
COPY . .

# Build the project
RUN cd board-game-engine && cargo build --bin rollup
